# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradF <- function(func, xnow, h) {
    .Call('_maotai_gradF', PACKAGE = 'maotai', func, xnow, h)
}

cppsub_2007Wang <- function(V0, mm, d, Spu, Stu, maxiter, eps) {
    .Call('_maotai_cppsub_2007Wang', PACKAGE = 'maotai', V0, mm, d, Spu, Stu, maxiter, eps)
}

